### ISSUE TITLE
Add a very nice border for algorithm image or write algorithm

### ISSUE THREAD

**Issue by vladbeklenyshchev** [vladbeklenyshchev/optimization-algorithms-website#30]
Add nice border (it's like create a Christmas card :smile: )
![image](https://cloud.githubusercontent.com/assets/11027650/19886114/90b368aa-a02a-11e6-9031-365f37fe792c.png)

Write algorithm - write by hands (we can use LaTex to diplay formulas). Actually, I think it's a very appropriate solution.

**Comment by TanyaPilipenko** [comment]
I won't write algorithms by hands. It is very-very long. I will make all pictures equal on width and make beautiful border.

**Comment by vladbeklenyshchev** [comment]
Ok. Fine. I want you to create border something like this :)
![image](https://cloud.githubusercontent.com/assets/11027650/19887291/4411fca4-a030-11e6-8d51-c70b711a8fe9.png)

**Comment by TanyaPilipenko** [comment]
Ok. I like this. I will try=)
