### ISSUE TITLE
Сhoose a right palette for website

### ISSUE THREAD

**Issue by vladbeklenyshchev** [vladbeklenyshchev/optimization-algorithms-website#31]
I thought two weeks ago about palette like football or.. [billiard](https://ru.wikipedia.org/wiki/%D0%91%D0%B8%D0%BB%D1%8C%D1%8F%D1%80%D0%B4) with green desk) :)

In particular I want to change this background color)
![image](https://cloud.githubusercontent.com/assets/11027650/19886361/8d75c146-a02b-11e6-807d-36a6ba33b464.png)

**Comment by vladbeklenyshchev** [comment]
Also I want to change this style color
![image](https://cloud.githubusercontent.com/assets/11027650/19886609/b3d6067e-a02c-11e6-8a4d-ceae3adcfee4.png)

**Comment by TanyaPilipenko** [comment]
But I changed palette. Did you look?

**Comment by vladbeklenyshchev** [comment]
Where should I look at it?)

**Comment by TanyaPilipenko** [comment]
At 11:57)
