### ISSUE TITLE
On page get value x, compute value y = f(x) and display it

### ISSUE THREAD

**Issue by vladbeklenyshchev** [vladbeklenyshchev/optimization-algorithms-website#32]

**Comment by TanyaPilipenko** [comment]
Please, write more info about this issue.

**Comment by vladbeklenyshchev** [comment]
In my script I don't compute y, but I return **x** to index page.
We need to compute **y**=f(**x**) value at index page. For this we can write another script (scripts) that will be store **y** value to our result field.
This task need us to display some basic features of our project)

**Comment by vladbeklenyshchev** [comment]
Finish the output inference in the all methods via next patterns:
`<h4><ins>ФОРМА ДЛЯ ВВОДА НАЧАЛЬНЫХ ЗНАЧЕНИЙ</ins></h4>
						<form class="form-horizontal" name="main_form" id="form-for-first-method">
							<div class="form-group">
				  				<label for="text" class="col-sm-5 control-label">Начальная точка X0 = </label>`
change id in here for corresponding method

Add script with corresponding values before button "Calculate":
`<script>
											function calculateViaFirstMethod(){
												//debugger;
												var form = document.getElementById('form-for-first-method');

												var elements = form.getElementsByClassName('form-control');
									
												var result = calcGradientDescentWithStaticStep([+elements[0].value, +elements[1].value], +elements[2].value, +elements[3].value, +elements[4].value)
												
												var modalWindow = document.getElementById('myModal1');

												var outputs = modalWindow.getElementsByClassName('form-control');
												outputs[0].value = result;
												outputs[1].value = f_x(result[0], result[1]);
											}
										</script>`
And change the onclick value:
`<button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal1" onclick="calculateViaFirstMethod()">Вычислить</button>
`
