### ISSUE TITLE
Resize buttons for website (and delete button for standard e)

### ISSUE THREAD

**Issue by vladbeklenyshchev** [vladbeklenyshchev/optimization-algorithms-website#34]
Do we need to resize these buttons? A think yeah.
![image](https://cloud.githubusercontent.com/assets/11027650/19886759/522f91dc-a02d-11e6-8faa-8a16eb435e08.png)
Also I want to remove this e button. I don't use it in my scripts.

**Comment by TanyaPilipenko** [comment]
Do you want to input field was small?

Okay, I will remove the field E.

**Comment by vladbeklenyshchev** [comment]
> Do you want to input field was small?
Actually, I don't know. It's difficult being product owner, scrum master and stakeholder I guess 😃   
I think we should resize buttons and watch what will be)

**Comment by TanyaPilipenko** [comment]
OK. I will resize buttons and align the center. And will watch)

**Comment by vladbeklenyshchev** [comment]
Cool 👍
