### ISSUE TITLE
Create padding/margin for header of website (stretching)

### ISSUE THREAD

**Issue by vladbeklenyshchev** [vladbeklenyshchev/optimization-algorithms-website#35]
So, as a user,  when I open website I want to see only a logo firstly.
![image](https://cloud.githubusercontent.com/assets/11027650/19886892/1c76e8b4-a02e-11e6-946f-026a3bac8dc8.png)

You can see this on [kaggle.com](https://www.kaggle.com/)
![image](https://cloud.githubusercontent.com/assets/11027650/19886890/1527f47c-a02e-11e6-9d66-f446dbfcc8be.png)

**Comment by TanyaPilipenko** [comment]
I remember about it. It will be done.
