### ISSUE TITLE
Write the algorithms in KaTex syntax

### ISSUE THREAD

**Issue by vladbeklenyshchev** [vladbeklenyshchev/optimization-algorithms-website#36]
We should write KaTex expressions in katex-algorithms-generator.js which is in js folder.
We can write algorithms that we have implemented in our tasks :)

Additional info:

-  all functions supported in KaTex - [link](https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX)
- different  matrix expressions - [link](http://latex.wikia.com/wiki/Matrix_environments)

**Comment by TanyaPilipenko** [comment]
Done 7/10.

**Comment by vladbeklenyshchev** [comment]
We need to write algorithms second-order in KaTex. Delay this until Saturday :)

**Comment by TanyaPilipenko** [comment]
I will try to do it)

**Comment by TanyaPilipenko** [comment]
Algorithms for first-order-methods done.
