### ISSUE TITLE
addition iteration for GaussSeidel method

### ISSUE THREAD

**Issue by vladbeklenyshchev** [vladbeklenyshchev/optimization-algorithms-website#52]
![image](https://cloud.githubusercontent.com/assets/11027650/20238044/d2ae1a3e-a8ea-11e6-865f-adcea38f190c.png)

So, I want to get a next iteration: something like this x = (-0,004; 0,015) and f(x) = 0.000197.

**Comment by TanyaPilipenko** [comment]
Done.
