### ISSUE TITLE
Something wrong with DFP method

### ISSUE THREAD

**Issue by vladbeklenyshchev** [vladbeklenyshchev/optimization-algorithms-website#53]
So I get next:
![image](https://cloud.githubusercontent.com/assets/11027650/20238058/38b9a898-a8eb-11e6-8edd-0c75a66b3494.png)

On debugging I saw that there was a NaN in multMatrixNumber function.
![image](https://cloud.githubusercontent.com/assets/11027650/20238069/6a74f0cc-a8eb-11e6-85cb-bb9f6e022e62.png)

**Comment by TanyaPilipenko** [comment]
Done.
